// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-g4NYH8AyoFKNUSVCwQD6OYfYLvvDBI',
    appId: '1:949008601909:web:2212cc74e8e88ec5def27c',
    messagingSenderId: '949008601909',
    projectId: 'shopping-app-sprints',
    authDomain: 'shopping-app-sprints.firebaseapp.com',
    storageBucket: 'shopping-app-sprints.firebasestorage.app',
    measurementId: 'G-CH3RHY3TLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRsc7n-w9qSeQ1_RWo5bQIcXHLd3NDzI',
    appId: '1:949008601909:android:2ee30e5ed2f767f0def27c',
    messagingSenderId: '949008601909',
    projectId: 'shopping-app-sprints',
    storageBucket: 'shopping-app-sprints.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9__kkQzVmkx4CNNX6cX8YlpIl9emkwB0',
    appId: '1:949008601909:ios:2a0ce28091d856afdef27c',
    messagingSenderId: '949008601909',
    projectId: 'shopping-app-sprints',
    storageBucket: 'shopping-app-sprints.firebasestorage.app',
    iosBundleId: 'com.example.shoppingAppInterface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9__kkQzVmkx4CNNX6cX8YlpIl9emkwB0',
    appId: '1:949008601909:ios:2a0ce28091d856afdef27c',
    messagingSenderId: '949008601909',
    projectId: 'shopping-app-sprints',
    storageBucket: 'shopping-app-sprints.firebasestorage.app',
    iosBundleId: 'com.example.shoppingAppInterface',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv-g4NYH8AyoFKNUSVCwQD6OYfYLvvDBI',
    appId: '1:949008601909:web:b7d933aec315bde7def27c',
    messagingSenderId: '949008601909',
    projectId: 'shopping-app-sprints',
    authDomain: 'shopping-app-sprints.firebaseapp.com',
    storageBucket: 'shopping-app-sprints.firebasestorage.app',
    measurementId: 'G-4TG0D4P8G4',
  );
}
